# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            "Maaha's blog"
tagline:          ''
description:      ''
url:              https://maahma.github.io/
baseurl:          ''

author:
  name:           'Maaha Ahmad'

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/maahma/maahma.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: maahaahmad